name: archicadeci
favicon: null
layout_spectrum: 0.4664719863794744
typography_spectrum: 0.49873746326193213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.29371499083936214
  lightness: 0.5693471971899271
  saturation: 0.2077559195458889
  rhythmicContrast: 0.8605204820632935
purpose: []
